---
- name: Plays for the Ubuntu VM
  hosts: ubuntu

  tasks:
  - name: Update apt cache and install Python 3
    apt:
      name: python3
      update_cache: yes

  - name: Stop firewall
    systemd:
      name: ufw
      state: stopped
      enabled: no


- name: Plays for the Centos VM
  hosts: centos

  tasks:
  - name: Update yum cache and install Python 3
    yum:
      name: python3
      update_cache: yes

  - name: Stop firewall
    service:
      name: firewalld
      state: stopped
      enabled: no

- name: file module and lineinfile
  hosts: all

  tasks:

  - name: Include variables from 'config.yaml'
    include_vars:
      file: config.yaml

  - name: create a file called 'UpdateHelloworld' in the '/' directory
    file:
      path: '/UpdateHelloWorld'
      state: touch
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'
    vars:
      user: vagrant

  - name: Insert a line inside the 'UpdateHelloWorld' file
    lineinfile:
      path: '/UpdateHelloWorld'
      line: 'This is a file created and updated using the file lineinfile modules.'
      state: present

  - name: Copy 'myname' to the /home/vagrant directory
    copy:
      src: myname
      dest: "/home/{{ user }}/myname"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'

  - name: View content of 'myname'
    shell: "cat /home/{{ user }}/myname"
    register: output

  - name: Show output of 'myname'
    debug:
      var: output
